DROP DATABASE IF EXISTS farmsservice;
DROP USER IF EXISTS `farms_service`@`%`;
CREATE DATABASE IF NOT EXISTS farmsservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `farms_service`@`%` INDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW,
SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `farmsservice`.* TO `farms_service`@`%`;
FLUSH RPIVILEGES;